language: cpp
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
    - ARDUINO_IDE_VERSION="1.8.12"

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
   
install:
   - arduino --install-library "Smartcar shield"
   - arduino --install-library "VL53L0X"
   - arduino --install-library "ESP32 AnalogWrite"
   - arduino --install-library "ServoESP32"
   - arduino --install-library "WifiLocation"

script:
   - build_platform esp32

after_success:
#  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
# - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
